### ISSUE TITLE
404 Installing GCC

### ISSUE THREAD

**Issue by kevinlinxc** [NumesSanguis/pyzmq-docker#2]
When running the Dockerfile I get 
```
2.325 E: Failed to fetch http://deb.debian.org/debian/dists/stretch/main/binary-arm64/Packages  404  Not Found
2.325 E: Failed to fetch http://deb.debian.org/debian/dists/stretch-updates/main/binary-arm64/Packages  404  Not Found
```

You should consider implementing a fix like https://unix.stackexchange.com/a/743865 or updating to a new base image

**Comment by NumesSanguis** [comment]
Fixed in PR: #3 

Thanks for the solution you mentioned in #1 . Bumping the version of the Python Docker image indeed solved the issue.
